import type { Metadata } from "next";
import { Geist, Poppins } from "next/font/google";
import localFont from "next/font/local"; 
import "./globals.css";

const poppins = Poppins({
    subsets: ["latin"],
    weight: ["400", "700"],
    variable: "--font-poppins"
})

const geistSans = Geist({
    subsets: ["latin"],
    weight: ["400", "700"],
    variable: "--font-geist-sans"
})

const barriecito = localFont({
    src: "../assets/fonts/Barriecito-Regular.ttf",
    variable: "--font-barriecito"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${poppins.variable} ${barriecito.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
